// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6szQT3XPIEk7B18M6dhabdKDJjpEbUQs',
    appId: '1:433033604007:web:cd980d0addfa8ddc5ca482',
    messagingSenderId: '433033604007',
    projectId: 'disastermanagementapp-b5d15',
    authDomain: 'disastermanagementapp-b5d15.firebaseapp.com',
    databaseURL: 'https://disastermanagementapp-b5d15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disastermanagementapp-b5d15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLNCRCTUlR7vtiMssDJ4wXzr1kTae2AY',
    appId: '1:433033604007:android:f7fd69ada51088c35ca482',
    messagingSenderId: '433033604007',
    projectId: 'disastermanagementapp-b5d15',
    databaseURL: 'https://disastermanagementapp-b5d15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disastermanagementapp-b5d15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Jng_7D6gwCSBy5XxEyFNiNRxKEdOzIA',
    appId: '1:433033604007:ios:dd8de47e609840685ca482',
    messagingSenderId: '433033604007',
    projectId: 'disastermanagementapp-b5d15',
    databaseURL: 'https://disastermanagementapp-b5d15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disastermanagementapp-b5d15.firebasestorage.app',
    iosBundleId: 'com.example.disaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Jng_7D6gwCSBy5XxEyFNiNRxKEdOzIA',
    appId: '1:433033604007:ios:dd8de47e609840685ca482',
    messagingSenderId: '433033604007',
    projectId: 'disastermanagementapp-b5d15',
    databaseURL: 'https://disastermanagementapp-b5d15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disastermanagementapp-b5d15.firebasestorage.app',
    iosBundleId: 'com.example.disaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6szQT3XPIEk7B18M6dhabdKDJjpEbUQs',
    appId: '1:433033604007:web:a2eecb653cb7e0195ca482',
    messagingSenderId: '433033604007',
    projectId: 'disastermanagementapp-b5d15',
    authDomain: 'disastermanagementapp-b5d15.firebaseapp.com',
    databaseURL: 'https://disastermanagementapp-b5d15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disastermanagementapp-b5d15.firebasestorage.app',
  );
}
